{
 "title": "Grafana Sensors Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Total Normal Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 } },
  { "title": "Total Firing Alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 } },
  { "title": "Pending Alerts", "type": "alertlist", "gridPos": { "h": 17, "w": 12, "x": 0, "y": 4 } },
  { "title": "Firing Alerts", "type": "alertlist", "gridPos": { "h": 17, "w": 12, "x": 12, "y": 4 } }
 ]
}
{
 "title": "All Sensor Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All Alerts",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"alerts\")\r\n  |> filter(fn: (r) => r._field == \"message\")\r\n  |> group(columns: [])\r\n  |> keep(columns: [\"_time\", \"field_id\", \"_value\"])\r\n  |> rename(columns: {_value: \"Message\"})\r\n  |> rename(columns: {_time: \"Fired At\"})\r\n  |> rename(columns: {field_id: \"Field ID\"})\r\n"
    }
   ]
  }
 ]
}
{
 "title": "Sensors2",
 "time": { "from": "2026-02-26T01:49:36.604Z", "to": "2026-02-26T01:49:36.605Z" },
 "templating": {
  "list": [
   {
    "name": "sensor_client_id",
    "label": "Sensor Identifier",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"agrosolutions-bucket\",\r\n  tag: \"sensor_client_id\"\r\n)"
    }
   },
   {
    "name": "field_id",
    "label": "Field Identifier",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"agrosolutions-bucket\",\r\n  tag: \"field_id\"\r\n)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sensor ${sensor_client_id}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Datas",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"agro_sensors\")\r\n  |> filter(fn: (r) => r.sensor_client_id == \"${sensor_client_id}\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\r\n      \"_time\",\r\n      \"soil_moisture_percent\",\r\n      \"air_temperature_c\",\r\n      \"precipitation_mm\",\r\n      \"air_humidity_percent\",\r\n      \"soil_ph\",\r\n      \"wind_speed_kmh\",\r\n      \"data_quality_score\"\r\n  ])\r\n  |> rename(columns: {\r\n      \"soil_moisture_percent\": \"Soil Moisture (%)\",\r\n      \"air_temperature_c\": \"Air Temp (°C)\",\r\n      \"precipitation_mm\": \"Precipitation (mm)\",\r\n      \"air_humidity_percent\": \"Air Humidity (%)\",\r\n      \"soil_ph\": \"Soil pH\",\r\n      \"wind_speed_kmh\": \"Wind Speed (km/h)\",\r\n      \"data_quality_score\": \"Data Quality\"\r\n  })"
    }
   ]
  },
  { "title": "Field ${field_id}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"agro_sensors\" and\r\n    r._field == \"status_id\" and\r\n    r.field_id == \"${field_id}\"\r\n  )\r\n  |> last()\r\n  |> keep(columns: [\"field_id\", \"_value\"])\r\n  |> rename(columns: {_value: \"status_id\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r._measurement == \"alerts\")\r\n  |> filter(fn: (r) => r.field_id == \"${field_id}\")\r\n  |> filter(fn: (r) => r._field == \"message\")\r\n  |> group(columns: [])\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> rename(columns: {_time: \"Fired At\"})\r\n  |> rename(columns: {_value: \"Message\"})"
    }
   ]
  }
 ]
}
{
 "title": "Weather - São Paulo",
 "time": { "from": "2026-03-02T05:00:00.000Z", "to": "2026-03-03T03:00:00.000Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Temperature (Cº)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"weather_current\")\r\n  |> filter(fn: (r) => r.city == \"sao_paulo\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"weather_current\")\r\n  |> filter(fn: (r) => r.city == \"sao_paulo\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Precipitation (mm)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"weather_current\")\r\n  |> filter(fn: (r) => r.city == \"sao_paulo\")\r\n  |> filter(fn: (r) => r._field == \"precipitation\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Rain Probability (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"weather_current\")\r\n  |> filter(fn: (r) => r.city == \"sao_paulo\")\r\n  |> filter(fn: (r) => r._field == \"rain_probability\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Wind Speed (km/h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"weather_current\")\r\n  |> filter(fn: (r) => r.city == \"sao_paulo\")\r\n  |> filter(fn: (r) => r._field == \"wind_speed\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Weather Condition",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"weather_current\")\r\n  |> filter(fn: (r) => r._field == \"weather_desc\")\r\n  |> last()"
    }
   ]
  },
  { "title": "Next 7 Days", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "import \"experimental\"\r\n\r\nfrom(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: now(), stop: experimental.addDuration(d: 7d, to: now()))\r\n  |> filter(fn: (r) => r._measurement == \"weather_forecast\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "query": "import \"experimental\"\r\n\r\nfrom(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: now(), stop: experimental.addDuration(d: 7d, to: now()))\r\n  |> filter(fn: (r) => r._measurement == \"weather_forecast\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "query": "import \"experimental\"\r\n\r\nfrom(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: now(), stop: experimental.addDuration(d: 7d, to: now()))\r\n  |> filter(fn: (r) => r._measurement == \"weather_forecast\")\r\n  |> filter(fn: (r) => r._field == \"precipitation\")\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Rain Probability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "import \"experimental\"\r\n\r\nfrom(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: now(), stop: experimental.addDuration(d: 7d, to: now()))\r\n  |> filter(fn: (r) => r._measurement == \"weather_forecast\")\r\n  |> filter(fn: (r) => r._field == \"rain_probability\")\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "query": "import \"experimental\"\r\n\r\nfrom(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: now(), stop: experimental.addDuration(d: 7d, to: now()))\r\n  |> filter(fn: (r) => r._measurement == \"weather_forecast\")\r\n  |> filter(fn: (r) => r._field == \"wind_speed\")\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Weather Condition",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "query": "import \"experimental\"\r\n\r\nfrom(bucket: \"agrosolutions-bucket\")\r\n  |> range(start: now(), stop: experimental.addDuration(d: 7d, to: now()))\r\n  |> filter(fn: (r) => r._measurement == \"weather_forecast\")\r\n  |> filter(fn: (r) => r._field == \"weather_desc\")\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  }
 ]
}